version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input --clear && gunicorn savannah.wsgi:application --bind 0.0.0.0:8000"
    container_name: savanna_web_service
    volumes:
          - static_volume:/home/savannah/web/staticfiles
    env_file: .env
    expose:
      - 8000
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
          - static_volume:/home/savannah/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes: 
  postgres-data:
  static_volume: